# Generated by Django 4.0.1 on 2022-01-17 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.TextField()),
                ('body', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='TripEntry',
            new_name='Trip',
        ),
        migrations.DeleteModel(
            name='EntryDetail',
        ),
        migrations.AddField(
            model_name='entry',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='travel_app.trip'),
        ),
    ]
